export const FETCH_ARTIST = "FETCH_ARTIST";
export const FETCH_ARTIST_COMPLETED = "FETCH_ARTIST_COMPLETED";
export const FETCH_ARTIST_REJECTED = "FETCH_ARTIST_REJECTED";

export const UPDATE_ARTIST_SEARCH_FORM = "UPDATE_ARTIST_SEARCH_FORM";
